

spring:
  application:
    name: entertainment
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123@
    url: 'jdbc:mysql://localhost:3306/entertainment?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8'
    hikari:
      pool-name: selfHikariCP
      connection-test-query: SELECT 1
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 30000
      login-timeout: 5
      max-lifetime: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false
  jpa:
    database: mysql
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_del
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:mapper/*.xml

server:
  port: 9018